name: CI

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ">=1.19.5"
      # Generate and publish a copy of our generated SBOM to Manifest
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@main
        id: transmit
        with:
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          sbomVersion: ""
          sbomName: testing-go-mod-name
          sbomOutput: cyclonedx-json
 