name: CI

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ">=1.19.5"
      - uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: ./bom.json
          artifact-name: bom.json
          format: cyclonedx-json
      # Transmit a copy of our generated SBOM to Manifest
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@main
        id: transmit
        with:
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          bomFilePath: "./bom.json"
          sbom-version: ""
          sbom-name: testing-go-mod-name
          sbom-output: cyclonedx-json
 